#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Aug 17, 2015 04:00:17 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#
    ttk::style configure Menu -background #d9d9d9
    ttk::style configure Menu -foreground #000000
    ttk::style configure Menu -font TkDefaultFont
    menu .pop59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 1 
    vTcl:DefineAlias ".pop59" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x447+672+296
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 2556 2494
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "RD-100 AP v1.1 PPT Program"
    vTcl:DefineAlias "$top" "Toplevel" vTcl:Toplevel:WidgetProc "" 1
    text $top.tex39 \
        -background {#c0c0c0} -font TkTextFont -foreground black -height 104 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 584 -wrap word 
    .top37.tex39 configure -font TkTextFont
    .top37.tex39 insert end text
    vTcl:DefineAlias "$top.tex39" "Text1" vTcl:WidgetProc "Toplevel" 1
    label $top.lab40 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Console: 
    vTcl:DefineAlias "$top.lab40" "Label1" vTcl:WidgetProc "Toplevel" 1
    canvas $top.can41 \
        -background white -borderwidth 2 -closeenough 1.0 -height 283 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground {#c4c4c4} \
        -selectforeground black -width 386 
    vTcl:DefineAlias "$top.can41" "Canvas1" vTcl:WidgetProc "Toplevel" 1
    button $top.but42 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text StartTest 
    vTcl:DefineAlias "$top.but42" "StartTest" vTcl:WidgetProc "Toplevel" 1
    button $top.but43 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Stop Test} 
    vTcl:DefineAlias "$top.but43" "StopTest" vTcl:WidgetProc "Toplevel" 1
    checkbutton $top.che49 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify left -text {Print Test Receipt} \
        -variable che49 
    vTcl:DefineAlias "$top.che49" "PrintOption" vTcl:WidgetProc "Toplevel" 1
    ttk::progressbar $top.tPr56
    vTcl:DefineAlias "$top.tPr56" "TProgressbar1" vTcl:WidgetProc "Toplevel" 1
    label $top.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Progress: 
    vTcl:DefineAlias "$top.lab58" "Label5" vTcl:WidgetProc "Toplevel" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tex39 \
        -in $top -x 10 -y 340 -width 584 -height 104 -anchor nw \
        -bordermode ignore 
    place $top.lab40 \
        -in $top -x 10 -y 318 -width 52 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.can41 \
        -in $top -x 10 -y 10 -width 386 -height 283 -anchor nw \
        -bordermode ignore 
    place $top.but42 \
        -in $top -x 410 -y 15 -width 177 -height 134 -anchor nw \
        -bordermode ignore 
    place $top.but43 \
        -in $top -x 410 -y 154 -width 177 -height 134 -anchor nw \
        -bordermode ignore 
    place $top.che49 \
        -in $top -x 469 -y 299 -width 120 -height 25 -anchor nw \
        -bordermode ignore 
    place $top.tPr56 \
        -in $top -x 70 -y 300 -width 390 -height 22 -anchor nw \
        -bordermode ignore 
    place $top.lab58 \
        -in $top -x 10 -y 297 -width 54 -height 21 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

